/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AwcInput {
        "color": string;
        "id": string;
        "name": string;
        "placeholder": string;
    }
    interface AwcTab {
        "id": string;
        "name": string;
    }
    interface AwcTabGroup {
    }
}
declare global {
    interface HTMLAwcInputElement extends Components.AwcInput, HTMLStencilElement {
    }
    var HTMLAwcInputElement: {
        prototype: HTMLAwcInputElement;
        new (): HTMLAwcInputElement;
    };
    interface HTMLAwcTabElement extends Components.AwcTab, HTMLStencilElement {
    }
    var HTMLAwcTabElement: {
        prototype: HTMLAwcTabElement;
        new (): HTMLAwcTabElement;
    };
    interface HTMLAwcTabGroupElement extends Components.AwcTabGroup, HTMLStencilElement {
    }
    var HTMLAwcTabGroupElement: {
        prototype: HTMLAwcTabGroupElement;
        new (): HTMLAwcTabGroupElement;
    };
    interface HTMLElementTagNameMap {
        "awc-input": HTMLAwcInputElement;
        "awc-tab": HTMLAwcTabElement;
        "awc-tab-group": HTMLAwcTabGroupElement;
    }
}
declare namespace LocalJSX {
    interface AwcInput {
        "color"?: string;
        "id"?: string;
        "name"?: string;
        "placeholder"?: string;
    }
    interface AwcTab {
        "id"?: string;
        "name"?: string;
    }
    interface AwcTabGroup {
    }
    interface IntrinsicElements {
        "awc-input": AwcInput;
        "awc-tab": AwcTab;
        "awc-tab-group": AwcTabGroup;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "awc-input": LocalJSX.AwcInput & JSXBase.HTMLAttributes<HTMLAwcInputElement>;
            "awc-tab": LocalJSX.AwcTab & JSXBase.HTMLAttributes<HTMLAwcTabElement>;
            "awc-tab-group": LocalJSX.AwcTabGroup & JSXBase.HTMLAttributes<HTMLAwcTabGroupElement>;
        }
    }
}
